In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)
print(a.shape)
b=np.array([[1,2,3],
           [4,5,6]])
print(b)
print(b.shape)


[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
c=np.arange(1,10, .2)
print(c)
print(c.shape)
d=np.linspace(1,10,20)
print(d)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
(45,)
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [8]:
c.ndim

1

In [9]:
print(c.reshape(9,5))

[[1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8]
 [3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8]
 [5.  5.2 5.4 5.6 5.8]
 [6.  6.2 6.4 6.6 6.8]
 [7.  7.2 7.4 7.6 7.8]
 [8.  8.2 8.4 8.6 8.8]
 [9.  9.2 9.4 9.6 9.8]]


In [12]:
np.random.randint(1,1000,(3,3))

array([[126, 266, 415],
       [986, 677, 850],
       [984, 756, 324]])

#MATHS IN NUMPY

In [16]:
x=np.array([
    [2,3,4],
    [5,6,7]
])
y=np.array([
    [1,2,3],
    [4,7,9]
])
print(x+y)
print(x-y)
print(x*y)
print(x**y)
print(x/y)
print(x%y)
print(x*2)

[[ 3  5  7]
 [ 9 13 16]]
[[ 1  1  1]
 [ 1 -1 -2]]
[[ 2  6 12]
 [20 42 63]]
[[       2        9       64]
 [     625   279936 40353607]]
[[2.         1.5        1.33333333]
 [1.25       0.85714286 0.77777778]]
[[0 1 1]
 [1 6 7]]
[[ 4  6  8]
 [10 12 14]]


In [17]:
#matrix multiplication
print(x.dot(y))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [19]:
print(x.dot(y.T)) #transpose
print(np.matmul(x,y.T))
print(x@y.T)

[[ 20  65]
 [ 38 125]]
[[ 20  65]
 [ 38 125]]
[[ 20  65]
 [ 38 125]]


In [20]:
#statical function
print(x.sum()) #sum of all elements
print(x.sum(axis=0)) # sum of colums
print(x.sum(axis=1)) #sum of rows
print(x.mean())#mean of elements
print(x.std())#standard deviation
print(x.min())#min of all elements
print(x.max())#max of all elements
print(x.argmax())#index of max element
print(x.argmin())#index of min element

27
[ 7  9 11]
[ 9 18]
4.5
1.707825127659933
2
7
5
0


In [21]:
#trignmetric functions
print(np.sin(x))
print(np.tan(x))
print(np.cos(x))


[[ 0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866 ]]
[[-2.18503986 -0.14254654  1.15782128]
 [-3.38051501 -0.29100619  0.87144798]]
[[-0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225]]


In [22]:
#indexing n sclicing
print(x[0,0])
print(x[0,:])
print(x[:,0])
print(x[0:2,0:2])
print(x[:2])

2
[2 3 4]
[2 5]
[[2 3]
 [5 6]]
[[2 3 4]
 [5 6 7]]
